FROM node:22-alpine3.19
#postaviti radni direktorijum
WORKDIR /usr/src/app
#kopirati u radni dir samo listu paketa za install
COPY package*.json ./
RUN npm install
#prva tacka trenutni radni dir lokalno,druga tacka radni dir u kontejneru
COPY . .
RUN npm run build
CMD [ "npm","run","start:prod" ]